version: '3.8'

services:
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka-1:
    image: 'confluentinc/cp-kafka'
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - 9091:9091
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - BOOTSTRAP_SERVERS=kafka-1:9091,kafka-2:9092,kafka-3:9093
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper

  kafka-2:
    image: 'confluentinc/cp-kafka'
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - BOOTSTRAP_SERVERS=kafka-1:9091,kafka-2:9092,kafka-3:9093
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper

  kafka-3:
    image: 'confluentinc/cp-kafka'
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - BOOTSTRAP_SERVERS=kafka-1:9091,kafka-2:9092,kafka-3:9093
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper

networks:
  default:
    name: local-environment
    external: true
