version: '3.8'

services:
  queue:
    hostname: 'local'
    container_name: 'rabbitmq'
    image: rabbitmq:3.9-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data/rmq/data:/var/lib/rabbitmq/local/

networks:
  default:
    name: local-environment
    external: true