version: '3.8'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - '6379:6379'
      - '8001:8001' # RedisInsight
    volumes:
      - ./data/redis/data:/data

networks:
  default:
    name: local-environment
    external: true
